[package]
name = "macrospace"
version = "0.1.0"
edition = "2021"

[dependencies]
macrospace-core = {path = "core"}
macrospace-macros = {path = "macros"}

proc-macro2 = {version = "1.0"}
syn = {version = "2.0", features = ["fold"]}
quote = {version = "1.0"}
syn_derive = {version = "0.1"}
