[package]
name = "macrospace-core"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = {version = "2.0", features = ["full", "extra-traits"]}
proc-macro2 = {version = "1.0"}
quote = {version = "1.0"}
syn_derive = {version = "0.1"}
itertools = {version = "0.13"}
